# Generated by Django 4.1.5 on 2023-01-04 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=25)),
                ('profile', models.CharField(max_length=100)),
                ('specialist', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('number', models.IntegerField()),
                ('education', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254)),
                ('linkedin', models.CharField(max_length=500)),
                ('twitter', models.CharField(max_length=500)),
                ('github', models.CharField(max_length=500)),
                ('facebook', models.CharField(max_length=500)),
                ('whatsapp', models.IntegerField()),
                ('telegram', models.IntegerField()),
                ('address', models.CharField(max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
