# Generated by Django 4.1.5 on 2023-01-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='aboutme',
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
    ]
