# Generated by Django 4.1.5 on 2023-01-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0002_aboutme_aboutme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='aboutme',
            field=models.TextField(max_length=2000),
        ),
    ]
