# Generated by Django 4.1.5 on 2023-01-04 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0003_alter_aboutme_aboutme'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('email_add', models.EmailField(max_length=100)),
                ('subject_name', models.CharField(blank=True, max_length=50)),
                ('message', models.TextField(default='Male', max_length=50)),
            ],
        ),
    ]
